dist: xenial
sudo: required
services:
  - xvfb
language: python
addons:
  firefox: latest
  apt:
    packages:
      - google-chrome-stable

_version:
  two: &two
    language: python
    python: "2.7"
  three: &threesix
    language: python
    python: "3.6"
  three: &three
    language: python
    python: "3.7"

_browsers:
  firefox: &firefox-latest
    addons:
      firefox: latest
  firefox-esr: &firefox-esr
    addons:
      firefox: latest-esr
  firefox-nightly: &firefox-nightly
    addons:
      firefox: latest-nightly
  chrome: &chrome
    addons:
      chrome: stable

matrix:
  include:
  - env: TOXENV=flake8
    <<: *two
  - env: TOXENV=py27-unit
    <<: *two
  - env: TOXENV=py27-chrome
    <<: *two
    <<: *chrome
  - env: TOXENV=py27-firefox
    <<: *two
    <<: *firefox-nightly
  - env: TOXENV=flake8
    <<: *three
  - env: TOXENV=py37-unit
    <<: *three
  - env: TOXENV=py37-chrome
    <<: *three
    <<: *chrome
  - env: TOXENV=py37-firefox
    <<: *three
    <<: *firefox-nightly
  - env: TOXENV=py37-example
    <<: *three
    <<: *chrome
  - env: TOXENV=flake8
    <<: *threesix
  - env: TOXENV=py36-unit
    <<: *threesix
  - env: TOXENV=py36-chrome
    <<: *threesix
    <<: *chrome
before_install:
- chmod +x ./travis.sh
install:
- pip install tox-travis
before_script:
- ./travis.sh
script:
- tox
